# Generated by Django 2.2.1 on 2019-05-25 17:13

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questionary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Тело анкеты')),
                ('questionary', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Тело анкеты')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Дата и время модификации')),
            ],
            options={
                'db_table': 'questionary_questionary',
            },
        ),
        migrations.CreateModel(
            name='QuestionaryStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Заполнена'), (1, 'Отправлена на перезаполнение'), (2, 'Принята'), (3, 'Отклонена')], verbose_name='Статус анкеты')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий проверяющего')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Дата и время модификации')),
                ('questionary', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='questionary_status', to='questionary.Questionary', verbose_name='Тело анкеты')),
            ],
            options={
                'db_table': 'questionary_questionary_status',
            },
        ),
    ]
