# Generated by Django 2.2.1 on 2019-05-25 18:45

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionaryFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fields', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Поля анкеты')),
                ('options', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Справочники')),
            ],
            options={
                'db_table': 'questionary_questionary_fields',
            },
        ),
    ]
