# Generated by Django 2.2.1 on 2019-05-26 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionary', '0002_questionaryfields'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('template', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'questionary_document_template',
            },
        ),
    ]
