# Generated by Django 2.2.1 on 2019-05-26 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionary', '0003_documenttemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionary',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
